### ISSUE TITLE
Remediate Vulnerability: Vulnerable Javascript Library

### ISSUE THREAD

**Issue by aaronstephenson** [USGS-WiM/WLERA#156]
Acunetix scan reports this app is using jQuery 3.3.1 and should be updated.

**Comment by BlakeDraper** [comment]
jQuery updated to 3.4.1 and code deployed to server. Not entirely clear if v3.4.1 will fully remediate, but latest (3.5.0) caused cascading issues with other dependencies which will be a much more involved process to address. If Acunetix still does like this, we'll cross that bridge.
