### ISSUE TITLE
Touch Up Print Product

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/WLERA#84]
- [x]  Add "Restoration Index Values" in the legend title to call out the numbers listed there

- [x] Add a north arrow

- [x] Remove the data sources (not the web site URL).

As per:

> The printout touch up has been mostly completed. Just three quick comments. 1. Add "Restoration Index Values" in the legend title to call out the numbers listed there, 2. Add a north arrow and 3. Remove the data sources (not the web site URL). Attached is what is currently coming out of the application

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Justin A. Saarinen, GISP

**Comment by BlakeDraper** [comment]
Done a while ago, but finally recording as done.
